@startuml
(*) --> "メニューを見る"
if  then
-->[カレンダーから選ぶ] "システムはカレンダーを表示"
--down--> "ユーザはカレンダーの日を指定"
--> "LineActionControllerがユーザの指示に対応するサービスを判別"
--> "Calendarサービスが空き時間のパラメータをLineBotClientに伝える"
--> "LineBotClientがユーザのLineにプッシュ送信する"
--> "システムはユーザ指定日の空き時間を表示"
--> "ユーザは空き時間ボタンをクリック"
---> (*)
else
    if "スタッフから選ぶ" then
        -> [スタッフから選ぶ]"システムはスタッフ一覧を表示"
        ->"ユーザーはスタッフを選択する"
        --> (*)
    else
        ->[コースから選ぶ] "システムはコース一覧を表示"
        ->"ユーザーはコースを選択する"
        -->[Ending process] (*)
    endif
endif

@enduml
